version: '3.3'
services:
  dashboard:
    build: ../dashboard-ui
    image: dashboard:latest
    ports:
      - "3000:3000"
    depends_on:
      - "processing"
      - "audit_log"
  receiver:
    build: ../Receiver
    image: receiver:latest
    ports:
      - "8080:8080"
    depends_on:
      - "kafka"
  storage:
    build: ../Storage
    image: storage:latest
    ports:
      - "8090:8090"
    depends_on:
      - "kafka"
  processing:
    build: ../Processing
    image: processing:latest
    network_mode: host
    depends_on:
    - "storage"
  audit_log:
    build: ../audit_log
    image: audit_log:latest
    ports:
      - "8110:8110"
    depends_on:
    - "kafka"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
    hostname: zookeeper
    volumes:
      - /home/azureuser/zookeeper/data:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: tanlab6a.eastus.cloudapp.azure.com # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://tanlab6a.eastus.cloudapp.azure.com:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/azureuser/kafka:/kafka/kafka-logs
    depends_on:
      - "zookeeper"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'events'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'hello123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'hello123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: